### ISSUE TITLE
Spec reporter swallowing database errors due to fixtures

### ISSUE THREAD

**Issue by jrhorn424** [kern/minitest-reporters#110]
```ruby
# test/test_helper.rb
# ...
require "minitest/reporters"
Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new

class ActiveSupport::TestCase
  fixtures :all
end
# ...
```
```ruby
# app/models/foo.rb
class Foo < ActiveRecord::Base
  has_one :bar
end

# app/models/bar.rb
class Bar < ActiveRecord::Base
  belongs_to :foo

  validates :foo, presence: true
end
```
```ruby
# db/migrate/...create_foos.rb
class CreateFoos < ActiveRecord::Migration
  def change
    create_table :foos do |t|
      t.string :baz
      # ... 
    end
  end
end

# db/migrate/...create_bars.rb
class CreateBars < ActiveRecord::Migration
  def change
    create_table :bars do |t|
      t.references :foos, index: true, null: false
      t.string :qux
      # ...
    end
  end
end
```
```yaml
# test/fixtures/foos.yml
---
one:
  baz: MyString

# test/fixtures/bars.yml
---
one:
  qux: MyString
```
```ruby
# test/fixtures/bar_test.rb
require 'test_helper'

class BarTest < ActiveSupport::TestCase
  test 'the truth' do
    assert true
  end
end
```

**Bug:** Running the test errors silently after a considerable pause. I'm using MySQL, but I suspect it isn't db-specific. 

**Expected:** Running the test errors, but not *silently*.

**Diagnosis:** What happens is that the test hangs when trying to load fixtures into the database. The actual error can be fixed by removing `validates :foo, presence: true` in `app/models/bar.rb`. Alternatively, one could add a random integer for `foo_id:` in `test/fixtures/bars.yml`.

My issue isn't with the error, but rather that the error is swallowed silently. Disabling `minitest-reporters` gives a useful backtrace for this error. So far, I've run into this issue twice, and in both cases the error originates when loading fixtures, but doesn't bubble up to the reporter.

This issue occurs whether or not `backtrace_silencers` are removed. I'm on `rails 3.2.16` using latest compatible `minitest` and `minitest-reporters`.

**Comment by stevendaniels** [comment]
I encountered the same error in a project that was using SQLite3. Unfortunately, the bug was due to an old version of SQLite3, so it isn't easily reproducible.

**Comment by os97673** [comment]
please re-open with easy-to-use test provided.
