### ISSUE TITLE
Update README to put invocation before Rails?

### ISSUE THREAD

**Issue by aripollak** [kern/minitest-reporters#119]
I've noticed that if I call `Minitest::Reporters.use!` from `test_helper.rb` after my environment has already been loaded under Rails 4.1, the regular Rails backtrace silencers don't take effect and the backtraces are gigantic. If the call happens before the environment loading, it works great. So the correct ordering looks like this:

```ruby
require 'minitest/reporters'
MiniTest::Reporters.use! [Minitest::Reporters::DefaultReporter.new(color: true, fast_fail: true)]

require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
```

Maybe this should be added to the README? Unless this is actually a bug and I'm doing something wrong.

**Comment by ciastek** [comment]
I've reproduced the problem with fresh [Rails 4.2 demo](
https://github.com/ciastek/rails-4-minitest-reporters).
[fail](https://github.com/ciastek/rails-4-minitest-reporters/tree/fail) - ([diff](https://github.com/ciastek/rails-4-minitest-reporters/commit/6153401e490b2aacec0a451623b9755ff631475e)) - [master](https://github.com/ciastek/rails-4-minitest-reporters/tree/master)

**Comment by os97673** [comment]
Was able to reproduce the problem: I see the long backtrace.

**Comment by os97673** [comment]
please try 1.1.0.beta3 and let me know if it helps.

**Comment by ciastek** [comment]
1.1.0.beta3 resolves the problem: [beta3](https://github.com/ciastek/rails-4-minitest-reporters/tree/beta3).
Thank you!
