### ISSUE TITLE
Should not colorize redirected output

### ISSUE THREAD

**Issue by suy** [kern/minitest-reporters#134]
Several of the minitest reporters send escape codes that only a real terminal is able to understand. When the output is redirected to a file or a pager (`rake test > notes.txt` or `rake test | nopaste`), or is run through a text editor that parses that output, the color codes (or the progress bar) should fall back to just the text.

**Comment by os97673** [comment]
could you please be a little bit more specific.  Which particular reporter does this for redirected output?

**Comment by suy** [comment]
Good point, I forgot that. I tried SpecReporter, and ProgressReporter. All have the same issue. Oddly, specifying DefaultReporter explicitly I don't have the problem, but not specifying any reporter I do.

**Comment by tadman** [comment]
The [patch I've submitted](https://github.com/kern/minitest-reporters/pull/135) should address this issue. Non-TTY situations no longer use ANSI.

**Comment by os97673** [comment]
@suy please try 1.0.10, let me know if it doesn't work for you

**Comment by suy** [comment]
Thank you! Works for me.
