### ISSUE TITLE
Avoid detailed information skipped tests in the report

### ISSUE THREAD

**Issue by JikkuJose** [kern/minitest-reporters#136]
Is there a way to avoid detailed messages associated with skipped tests? Also, is there a way to disable randomization of tests.

**Comment by os97673** [comment]
randomization is not something minitest-reporters provide but this is functionality provided by minitest, as far as I remember there is an option to provide some specific seed to have fixed order.
As for detatiled information for skipped tests: what formatter are you using?

**Comment by JikkuJose** [comment]
I am using DefaultReporter

**Comment by os97673** [comment]
you van pass false as value for :detailed_skip param to the ctor (seehttps://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/default_reporter.rb#L16)

**Comment by JikkuJose** [comment]
Wow, thanks!! It worked so well!
