### ISSUE TITLE
issues with mini_backtrace?

### ISSUE THREAD

**Issue by maoshouse** [kern/minitest-reporters#142]
Hey, I'm not sure if I should be asking about this here as this seems to be more of a mini_backtrace issue, but messing around with the provided reporters produced different results, so perhaps there is more to this. I apologize in advance if I should really be posting in the mini_backtrace project.

The :test of my gemfile consists of:

group :test do
  gem 'minitest-reporters', '1.0.10'
  gem 'mini_backtrace',     '0.1.3'
  gem 'minitest-rails-capybara', '2.1.1'
end

If I use anything other than the DefaultReporter, if a test fails, the backtrace goes a little bit crazy. If I use DefaultReporter, the red/green works just fine and none of this happens.

The error I get with anything other than the default reporter is:
/Users/maoshouse/.rvm/gems/ruby-2.1.5/gems/mini_backtrace-0.1.3/lib/mini_backtrace/unit.rb:4:in `filter_backtrace_with_rails': undefined method `backtrace_cleaner' for Minitest::Rails:Module (NoMethodError)
...

Can anyone lend a hand? Thanks!

**Comment by os97673** [comment]
I believe that this is either a mini_backtrace's issue or you shouldn't use it with ruby 2.1.5 because it states that it is for Rails 3 and ruby 1.9 (its doc says "This includes everyone using Rails 3 with Ruby 1.9.")
As for the difference in the behavior you see: I think that DefaultReporter just do not call `#filter_backtrace` and so you do not see the exception in this case.
Thus I'd suggest to contact author or mini_backtrace to resolve the issue, but feel free to ping me again if you will need any changes on reporters' side

**Comment by frostblooded** [comment]
I'd like to know what happened, because I too have a problem with this now. I get this when I try to use fill_in in a very simple test:

` test "canActuallyLogin" do
    visit new_company_session_path

    fill_in 'Name', with: 'SomeRandomNameKappa'
    fill_in 'Email', with: 'somerandommail@example.org'
    fill_in 'Password', with: 'foobarbarbar'
    fill_in 'Password confirmation', with: 'foobarbarbar'
    click_button 'Sign up'

    assert_content page,  'A message with a confirmation link has been sent to your email address. Please follow the link to activate your account.'
  end`

**Comment by os97673** [comment]
I will happy to investigate the problem if you provide a small executable test (which I can clone and run)

**Comment by frostblooded** [comment]
Actually, I found what the solution was after [asking around](https://www.reddit.com/r/rails/comments/4xy07a/im_having_a_pretty_odd_error_with_capybara_and_a/). [mini_backtrace](https://github.com/stympy/faker/issues/660#issuecomment-239350191) seems to be the troublemaker here. It throws this error when used with minitest-reporters. In my situation I simply removed mini_backtrace as I didn't really need it, but I still had it from the Gemfile provided by the [Ruby on Rails Tutorial book](https://www.railstutorial.org/book).

Anyway, if anyone actually needs to have both of the gems working, I found a [fix](https://github.com/metaskills/mini_backtrace/pull/2) in an open pull request on mini_backtrace's repository.

**Comment by os97673** [comment]
thanks for your time and investigation.
