### ISSUE TITLE
Generate a single report for all test classes

### ISSUE THREAD

**Issue by leo-altiscale** [kern/minitest-reporters#143]
Hi
  I have two test classes and a rakefile to kick off these two test classes, I want to use minitest-reporters to generate a single report for these two test classes.

  I "require test_helper.rb" in each of the test classes, when I use rake to run these two test classes parallel,  test_helper.rb has been called twice, one for each of the two classes, then the 2nd report overwrite the first report.

  What I can do to make a single report for these two test classes?

  I have tried googled to see if anyone else met the same issue but can not find any, Thx for help 
  the picture below shows what I have  

![minitest-report](https://cloud.githubusercontent.com/assets/11167652/6762552/a4aad128-cf1f-11e4-94e3-9ed2373ec3f6.png)

Leo

**Comment by leo-altiscale** [comment]
this is my test_helper.rb

equire "minitest/reporters"
Minitest::Reporters.use! [Minitest::Reporters::SpecReporter.new, Minitest::Reporters::JUnitReporter.new]

**Comment by os97673** [comment]
as far as I understand you need to make sure that test_helper is loaded only once.
E.g. you could try to load it in your Rakefile before running the tests (if you use thread to do this)
Or redirect reports to different files and merge them after the run.
Anyway there is nothing we could do on our side, thus 'm closing the ticket but this doesn't mean I will not  answer your questions ;)

**Comment by leo-altiscale** [comment]
Hi thx so much for your reply and suggestions. I'd really appreciate it!

I have actually tried the first solution you mentioned, I comment out the 'require test_helper.rb' in both the two test classes and only require 'test_helper.rb' in the rake file but what I got is as below, the program emptying the old test report at first but doesn't generate any new report at the end, plz let me know if I did anything wrong, cuz I figured this is supposed to work :)

![screen shot 2015-03-23 at 10 04 19 am](https://cloud.githubusercontent.com/assets/11167652/6785628/00c21a22-d144-11e4-8ee1-2b18f964ad8d.png)

for the 2nd solution, I think once I have more test classes like hundreds and thousand, it is a bit hard to manage in this " redirect reports to different files and merge" way, I'd prefer the first solution if it works

Thx so much

Leo

**Comment by leo-altiscale** [comment]
I am wondering if this minitest reporter test_helper.rb is a class specific thing and can NOT work for a bunch of classes in a folder?

**Comment by os97673** [comment]
> I am wondering if this minitest reporter test_helper.rb is a class specific thing and can NOT work for a bunch of classes in a folder?

it is not class specific thing, but it is process-specific thing.  It looks like you run several ruby processes and thus you need to merge the reports somehow.
It is hard to help w/o having a real code to play with.
If it is possible please share the code and I will see what can be done there.

**Comment by leo-altiscale** [comment]
Hi Oleg, how is weather in Russia? cold ? :) , thx for your quick reply. below is my rake file, basically I wana run my tests on browserstack parallel and yes I think by doing so, it starts multiple ruby processes to run tests which calls the test_helper.rb many times.

![rakefile](https://cloud.githubusercontent.com/assets/11167652/6838967/f9706ba2-d31e-11e4-874f-f0c7a2285120.png)

**Comment by leo-altiscale** [comment]
Parallel.map () do |browser| handles the threads/processes scheduling work, looking forward to your help, many thanks sent from California

Leo

**Comment by os97673** [comment]
So, since you have multiple process the only option I see it to save each report in separate file and merge them after :(

**Comment by leo-altiscale** [comment]
Hi Oleg
  Thx for your reply, then my question is how to specify where to write the test result in test_helper.rb, I can not find the solution online

  Below is my current test_helper.rb, what I need to add in this file to make writing the report to a specific directory. the default location is under test/test/reporter

![test-report-location](https://cloud.githubusercontent.com/assets/11167652/6852283/f809f684-d3a0-11e4-83bf-54797f5082a1.png)

**Comment by os97673** [comment]
JUnitReporter takes directory to which it will write as constructor's arg, while spec reporter just write to stdout, so you need to redirect it to some file.
IMHO it should be easier to merge reports from JUnitReporter

**Comment by leo-altiscale** [comment]
Hi Oleg
  Thx for your reply, could you give me more details on how to merge reports from JUnitReporter - the easier way. Or give me a example for this approach. What I need to change or add in my test_helper.rb

Thx
Leo

**Comment by os97673** [comment]
the reporter creates separate .xml file for every suite, so you just need to collect all files which will be created.

**Comment by leo-altiscale** [comment]
Hi Oleg
  I have a separate question here and I'd really appreciate if you know how
to solve it :), I am NOT a ruby expert

  I have a bunch of ruby selenium tests and I am using minitest.

my questions is
Is there any easy way to re-try failed test in ruby minitest? like what
TestNG provides retryAnaylze for java?


Leo

**Comment by os97673** [comment]
AFAIK minitest doesn't provide such functionality, but you should ask on minitest list (hope one does exist)

**Comment by leo-altiscale** [comment]
Hi Oleg
  Thx for you reply, I asked minitest list, they don't have such feature. I
think I am gonna implement some retryAnalyze for my purpose.

  Here I have another question about minitest-report

  I have a selenium test case named - test_linux_os_section, by pass
different params to the test, this test will be able to written once and
run on different environments (different browser+os combinations).

  The problem is, if I run this test_linux_os_section on 5 different envs,
when minitest report writing xml report, the 5 test case name will all be
test_linux_os_section, BUT I will distinguish the 5 tests on different envs
something like below

   test_linux_os_section-win-ff
   test_linux_os_section-osx-chrome
   test_linux_os_section-osx-safari
   test_linux_os_section-win-8
   test_linux_os_section-osx-ff


  Can give me some clue how I can achieve this by using minitest.

Thx so much
Leo








On Thu, Apr 16, 2015 at 11:30 PM, Oleg Sukhodolsky <notifications@github.com

**Comment by os97673** [comment]
So, you are asking how to create several artificial tests in minitest,  and again I'd suggest to ask this on minitest's list.
