### ISSUE TITLE
fast-fail option

### ISSUE THREAD

**Issue by jmarceli** [kern/minitest-reporters#144]
Hi,
I found `fast-fail` option for the default reporter (https://github.com/kern/minitest-reporters/pull/44), but is there any other option which will stop following tests after first failure?

**Comment by jmarceli** [comment]
It turns out to be quiet simple to add. So I manage to extend the SpecReporter which I use in my project with `fast_fail` option (see https://github.com/kern/minitest-reporters/pull/145).

**Comment by os97673** [comment]
as discussed in #145 the functionality you want should be implemented in in `minitest`, thus I'm closing the ticket.
