### ISSUE TITLE
Is there any way to disable Emptying at the beginning

### ISSUE THREAD

**Issue by leo-altiscale** [kern/minitest-reporters#146]
Hi
  I wana use Minitest::Reporters::JUnitReporter.new("reportj"), the junit report.
  But the process always emptying the old reports like below at the very begin, is there anyway that I can disable this emptying?

Emptying /Users/xxx/test/reportj

Thx
Leo

**Comment by leo-altiscale** [comment]
Because, I use test_helper.rb in a multi-thread environment, this empty thing will delete the reports generated by othe threads

**Comment by os97673** [comment]
Please check params of JUnitReporter's ctor (https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/junit_reporter.rb#L12)
;)

**Comment by leo-altiscale** [comment]
awesome, thx
