### ISSUE TITLE
adding Minitest::Reporters.use!(   Minitest::Reporters::DefaultReporter.new,   ENV,   Minitest.backtrace_filter ) breaks the reporters

### ISSUE THREAD

**Issue by cvandermeer** [kern/minitest-reporters#169]
After adding 
Minitest::Reporters.use!(
  Minitest::Reporters::DefaultReporter.new,
  ENV,
  Minitest.backtrace_filter
) 
to the test_helper file the reporters wont doesnt have any effect anymore and the backtrace silencers still arent working

**Comment by os97673** [comment]
please provide a test project (repository) which can be used to reproduce the problem

**Comment by os97673** [comment]
perhaps this is the same as #168?  Please test it with updated rails
