### ISSUE TITLE
Progress reporter: cursor disappears in byebug breakpoint

### ISSUE THREAD

**Issue by JoeCohen** [kern/minitest-reporters#172]
When I set a breakpoint in byebug and run tests using the Progress reporter, 
then there is no cursor in byebug when the test hits a breakpoint.
In the Default reporter, the cursor behave properly.

(Sorry for merely creating an issue -- as opposed to trying to fix it -- but I have no idea how to fix the Progress reporter so this doesn't happen.)

**Comment by os97673** [comment]
I'm not sure this is a Progress reporter's problem.  Imho byebug should be ready for situations when cursor is hidden by the program user debug and restore it.

**Comment by os97673** [comment]
BTW will be happy to help you to convince byebug's author ;)

**Comment by JoeCohen** [comment]
Oleg:
Thank you for the fast repose.  I will see if byebug can help.
Regards,
Joe
