### ISSUE TITLE
Cannot run tests?

### ISSUE THREAD

**Issue by gavinlaking** [kern/minitest-reporters#173]
Hi,

I've recently forked the project as I have an idea for a reporter I'd like to share with you via a pull request. I've produced it by extracting it from a current project. For my pull request, I'd like to write some tests to prove/show it works, but I am struggling to run the tests.

```
Source/minitest-reporters:feature/mean_time_reporter$ rake gallery
Gemfile Found, running with bundle exec
/home/gavinlaking/.rubies/ruby-2.2.3/bin/ruby: invalid option -2  (-h will show valid options) (RuntimeError)
```

I get the same if I try `rake`, (with or without `bundle exec`), and `rake -2` or `rake -h`. What's the secret sauce?

Kind Regards,

Gav

**Comment by os97673** [comment]
I do nothing special and rake does work for me :(
Perhaps you have some special version of rake?

**Comment by gavinlaking** [comment]
I'm using 10.4.2 by the looks of things. If you don't mind, I'll submit my pull request anyway, and perhaps I can create some tests once you've had a look over it. I'll invoke the "works on my machine" developer card for this! ;-)

Thanks,

Gav

**Comment by gavinlaking** [comment]
My apologies on this issue. I'd derped the `minitest-reporters` gem in my `.gem` directory and `rake` was using the broken version. Hanging my head in shame.
