### ISSUE TITLE
NoMethodError: undefined method `create_suite_started' for nil:NilClass

### ISSUE THREAD

**Issue by donv** [kern/minitest-reporters#175]
Hi!

Updated from minitest-reporters 1.0.20 to 1.1.0, and I now get the following exception:

```
NoMethodError: undefined method `create_suite_started' for nil:NilClass
             before_suite at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:82
              before_test at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-reporters-1.1.0/lib/minitest/reporters/base_reporter.rb:20
              before_test at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:90
  block in run_with_hooks at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46
                     each at org/jruby/RubyArray.java:1560
           run_with_hooks at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46
           run_one_method at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:781
           run_one_method at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:308
             block in run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:296
                     each at org/jruby/RubyArray.java:1560
             block in run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:295
                on_signal at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:334
        with_info_handler at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:321
                      run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:294
           block in __run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:155
                      map at org/jruby/RubyArray.java:2300
                    __run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:155
                      run at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:129
         block in autorun at /Users/uwe/.rvm/gems/jruby-head/gems/minitest-5.8.0/lib/minitest.rb:56
```

In the test_helper.rb we have

```ruby
Minitest::Reporters.use!
```

**Comment by os97673** [comment]
What version of RubyMine are you using?

**Comment by os97673** [comment]
Also is it possible to provide test project to reproduce the problem?

**Comment by dmagliola** [comment]
Hi,
Thank you for your comments on my other issue, sorry about the duplicate.

I'm using Rubymine 7.1

This is reproducible with my "sms_safe" gem.

https://github.com/dmagliola/sms_safe/

If you clone that and run bundle, it'll install minitest-reporters 1.1.0

If you manually change the Gemfile.lock to 1.0.20, tests will run. If you leave it as 1.1.0, you get Empty Test Suite.

Let me know if I can help in any way with this!
Daniel

**Comment by dmagliola** [comment]
So, to make sure I understand (sorry if I'm being dense)... To fix this issue I need to update RubyMine, correct?

**Comment by os97673** [comment]
You can just update one .rb file in RubyMine's installation

**Comment by os97673** [comment]
let me know if there will be any problems

**Comment by dmagliola** [comment]
Excellent, thank you!

**Comment by nmahoney-pivotal** [comment]
My tests run fine in iTerm, but I am getting the same error message when trying to run my tests in RubyMine. I have already upgraded RubyMine to 7.1.4 and upgraded Ruby to 2.2.3.

**Comment by os97673** [comment]
@nmahoney-pivotal have you tried to update the .rb file in RubyMine installation?

**Comment by nmahoney-pivotal** [comment]
Where can I find the .rb file, and how do I update it?

**Comment by os97673** [comment]
there is rb directory inside RubyMine's installation.
Check the commit linked to the issue to see what file should be updated and how.

**Comment by nmahoney-pivotal** [comment]
That fixed it. Thanks!

**Comment by ffabreti** [comment]
Worked for me (rubymine 6.3.3)
file: rb/testing/patch/testunit/minitest/rm_reporter_plugin.rb
