### ISSUE TITLE
Why disable formatters in vim

### ISSUE THREAD

**Issue by justinj656** [kern/minitest-reporters#180]
I just tried Reporters under vim, but I find it do not work. Then I discover the cause after I search the issues.

>Disable custom formatters when running under vim
>#166 opened on Jul 7 by aripollak 

However when I overwrite the **choose_reporters** method(as below), it actually works. The output of minitest is actually formatted and colorized.

    require 'minitest/autorun'
    require 'minitest/reporters'

    module Minitest
      module Reporters
        def self.choose_reporters(console_reporters, env)
          if env["TM_PID"]
            [RubyMateReporter.new]
          elsif env["RM_INFO"] || env["TEAMCITY_VERSION"]
            [RubyMineReporter.new]
          else
            Array(console_reporters)
          end
        end
      end
    end

    Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new

    class FlowTest < Minitest::Test
      def test_1
        assert_equal 4, 1+2
      end
      
      def test_2
        assert_equal 4, 4
      end
    end

![screenshot from 2015-09-27 19 03 50](https://cloud.githubusercontent.com/assets/6373811/10122389/890e057c-654a-11e5-9876-6a26a667bc8e.png)

**So, why Reporters is disabled under vim??**

**Comment by os97673** [comment]
I think this is the question for @aripollak (I'm not using vim)

**Comment by aripollak** [comment]
I think I explained it pretty well in the original PR?

> Vim's quickfix list does not support color codes and only recognizes errors from the default Minitest output formatter.

If you use, say, vim-rails to make :Rake run unit tests, you should be able to use the quickfix list to quickly jump to the line with the errors. But minitest-reporters changes the formatting and makes vim not be able to recognize the filenames & line numbers.

**Comment by os97673** [comment]
I think the explanation is complete.  If it is not I'd suggest to discuss this in the gitter channel I've created.

**Comment by justinj656** [comment]
Sorry for my unconsidered question. Surely, quickfix is a better choise to trace errors in vim despite the uncolorized output.

**Comment by jvanbaarsen** [comment]
@os97673 Would you be open to contributions to make this configurable? Since for example, I do use vim, but not outputting anything to Quickfix since that is showing messed up output.

So I'm running the tests in a TTY enabled env, but also via VIM (so the `ENV['VIM']` is set)

**Comment by os97673** [comment]
@jvanbaarsen am I correctly understand that VIM env.var. is set even when you run the tests in a TTY-enabled env?

**Comment by jvanbaarsen** [comment]
@os97673 Yes, I run my test via a test runner, and under the hood they just do: `!clear && bin/rake TESTFILE`. But this still does not have any formatting. (I assume when you do a `!` command, this gets run outside of the context of vim?

**Comment by os97673** [comment]
> I assume when you do a ! command, this gets run outside of the context of vim?

I do not know (since I do not use vim for development :(
Could you please print value of `ENV['VIM']` from your tests so we would be sure that we know the cause of the problem.  If it is I will be happy to get PR and discuss it (will need to invite @aripollak to the discussion)

**Comment by jvanbaarsen** [comment]
@os97673 The output is:
```
"/usr/local/Cellar/macvim/7.4-79/MacVim.app/Contents/Resources/vim"
```

**Comment by os97673** [comment]
So, I'm waiting for the PR ;)

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
@os97673 What do you think would be the best course of action? Add an option named `ignore_vim`? And if that is set to true, we always use the formatter, even when `ENV["VIM"]` is set?

**Comment by jvanbaarsen** [comment]
@os97673 I figured out another way we can do this, without having to change the behaviour of the gem. Since all the arguments @aripollak is presenting are valid. I now setup the minitestreporter as follow:

```ruby
Minitest::Reporters.use! [Minitest::Reporters::DefaultReporter.new(reporter_options)], ENV.delete("VIM")
```

This will enforce that the `ENV['VIM']` is not present, and thus always uses the reporter :-)

**Comment by os97673** [comment]
I'm not sure that this is exactly what you wanted originally, but if you are ok with this then I'm ok too ;)

**Comment by jvanbaarsen** [comment]
@os97673 Not exactly, but I don't think having an option in there for a specific editor is also terrible :-) So I'll take my loses and roll with this :-) Thanks for this awesome project!

**Comment by os97673** [comment]
you are welcome
