### ISSUE TITLE
SpecReporter not printing stacktrace

### ISSUE THREAD

**Issue by matt-riemer** [kern/minitest-reporters#184]
Hey all,

After upgrading from 1.0.20 to 1.1.2  the backtrace on the SpecReporter is no longer displayed.  It just doesn't print the backtrace for me anymore.

Rails4 app.

I was using

Minitest::Reporters.use!(Minitest::Reporters::SpecReporter.new)

but also tried

Minitest::Reporters.use!(Minitest::Reporters::SpecReporter.new, ENV, Minitest.backtrace_filter)

with no affect.  My test is just:

test 'assert something' do
  assert false
end

Help :)

**Comment by matt-riemer** [comment]
I've discovered that if I call

Rails.backtrace_cleaner.remove_silencers!

before or after declaring the Minitest::Reporters.use!(Minitest::Reporters::SpecReporter.new)

then I once again see the backtrace.  But it's the full one, not the truncated minitest backtrace filter.

Sorry, something has changed between 1.0.20 and 1.1.2 perhaps making the backtracer too restrictive?

Thanks

**Comment by os97673** [comment]
most likely this is caused by the fix for #119 (725a4ca88f73dc165b64a21fec16e5be2868d9eb) we are supposed to use Rails backtrace filter now.  But if you will that my understanding is wrong feel free to correct me ;)
