### ISSUE TITLE
Reporters should base time on `Minitest.clock_time`, not `Time.now`

### ISSUE THREAD

**Issue by gareth** [kern/minitest-reporters#186]
`minitest-reporter`'s (*MR*) `BaseReporter` sometimes reports how far through a test suite a failure happened, overriding `total_time` from `Minitest::StatisticsReporter`.

It does this because Minitest only sets `total_time` at the end of a suite, whereas MR wants to know this earlier (in the case of `fast_fail`, for example).

However, the [overriding method](https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/base_reporter.rb#L68) falls back to `Time.now` as its base to calculate duration, whereas Minitest (since [5.6.1](https://github.com/seattlerb/minitest/blob/master/History.rdoc#561--2015-04-27)) uses a different method, [`Minitest.clock_time`](https://github.com/seattlerb/minitest/blob/78d36807d99404dcbf27bab2091c150ffe3e3f74/lib/minitest.rb#L512), which may have a [different implementation](https://github.com/seattlerb/minitest/blob/78d36807d99404dcbf27bab2091c150ffe3e3f74/lib/minitest.rb#L786) depending on whether `Process::CLOCK_MONOTONIC` is available on the system.

MR should use `Minitest.clock_time` instead of `Time.now` if available, to avoid misreporting times in its reports.

**Comment by gavinlaking** [comment]
Quite happy to pick this up, if you want me to Oleg? (@os97673)

**Comment by os97673** [comment]
@gavinlaking any help is (always) welcome :)

**Comment by os97673** [comment]
Ok, so I'm closing the ticket since we have the PR which is supposed to fix it (hope it will be completed soon)

**Comment by gareth** [comment]
:+1:
