### ISSUE TITLE
Rails 5.0.0.beta3 Integration.

### ISSUE THREAD

**Issue by jonathan-soifer** [kern/minitest-reporters#201]
Hi,

I'm currently trying to use the Minitest Reporters with Rails 5b3 and it is not working.

Just wanted to know if someone's ever tried this before, if you're already testing with the new version and/or if I might have stumbled upon a "feature" :grin: 

Thank you

**Comment by gsusmonzon** [comment]
Hello, I am using it with rails 5 beta3 with no problems

Ensure your Gemfile contains both

```ruby
group :test do
  gem "minitest"
  gem 'minitest-reporters' #For minitest >= 5.0.0, minitest-reporters gem is not required.
end
```
Gemfile.lock tells I am using these versions

```ruby
minitest (5.8.4)
minitest-reporters (1.1.8) 
```

Ensure that your test_helper.rb (that is included in every tests)

```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'minitest/unit'
require 'minitest/autorun'
require 'rails/test_help'

Minitest::Reporters.use! Minitest::Reporters::ProgressReporter.new
....
```

**Comment by jonathan-soifer** [comment]
I switched the Rails version from 5 beta 3 to the latest release on the master branch and now it works :)

Thank you!
