### ISSUE TITLE
Stop printing on load

### ISSUE THREAD

**Issue by ptarjan** [kern/minitest-reporters#203]
If I load up https://github.com/kern/minitest-reporters/blob/e9bdfb79ae4f63971c179afb9fd18c57e1f0ecd7/lib/minitest/reporters/rubymine_reporter.rb#L10 I get an error printed out to my console just for the small act of referencing the constant `RubyMineReporter`. Can you only print that message when I actually try to use your reporter please?

(If you want to push back on my use-case, we have lots of static analysis tools which load all constants we can find and do things to them. Just by loading your constant we get STDOUT spew when we had no intention of running the reporter).

**Comment by os97673** [comment]
Just to clarify:  "loading your constant" mean "loading your file"?

**Comment by ptarjan** [comment]
Yes

**Comment by os97673** [comment]
fixed by 406cdc83de197bb92391a684f051434c44fe1ee3
Will contact RubyMine's team to let them time to test the change before releasing a new version.
