### ISSUE TITLE
I have created extension: minutest-reporters-json_reporter gem. Should I fork your project and do a PR?

### ISSUE THREAD

**Issue by edhowland** [kern/minitest-reporters#204]
Hi. I needed a JSON output from MiniTest. So I wrote a gem: minutest-reporters-json_reporter to do the job. Chris, the guy who wrote the book on MiniTest, suggested I should fork and issue a PR here. I would like your input before I attempt this. (I never have done a PR before.) The current GitHub repo is at : [https://github.com/edhowland/minitest-reporters-json_reporter

I have 2 general questions.
1. Is a JSON output format general purpose to be included in the main minutest-reporters gem?
2. I looked at the HTML and JUnit reporters and they place output in test/reports/... Is that a standard? 

Currently, I am sending JSON to stdout, but that can easily be changed to a File object.

Also, I am not doing anything at all with backtraces. I need to look at your backtrace filter to get a better handle. Frankly, how to handle BTs are a wide mystery to me.

Thanks, Ed](url)

**Comment by os97673** [comment]
> 1. Is a JSON output format general purpose to be included in the main minutest-reporters gem?

yep, why not :)

> 2. I looked at the HTML and JUnit reporters and they place output in test/reports/... Is that a standard?

it is "standard" for the gem ;)  It is better to follow the same approach in the gem just to make user's experience consistent.

> Also, I am not doing anything at all with backtraces. I need to look at your backtrace filter to get a better handle. Frankly, how to handle BTs are a wide mystery to me.

current backtrace filtering just filter out all minitest/minitest-reporters specific frames so user would see only "important" information in the printed backtrace.

**Comment by os97673** [comment]
I'm closing the ticket since there is nothing to do here. But I'm open to discussions so feel free to contact me in the gitter room (see link in README).

**Comment by edhowland** [comment]
Hi, Thanks. I will contact you when I have a PR.
Regards, Ed

Cheers,
Ed

Ed Howland
http://greenprogrammer.wordpress.com
http://twitter.com/ed_howland

**Comment by andyw8** [comment]
Hi @edhowland, I know it's been a while since this issue was opened, but I'm considering taking up this task to bring your reporter into minitest-reporters, is that ok with you?

**Comment by edhowland** [comment]
Hi. Yes it  is way all right with me. For background: Due to my poor health I have only enough time to work on my main project: Viper: The Hugely helpful, AmazinglyAccessable and Easily Extensible code and text editor optimized for screen reader users.
What I am wondering though is if you bring it into the main project, should I delete my repo or keep it for historical reasons?

Thanks for taking this on.
- Ed

**Comment by andyw8** [comment]
I think it's better to keep this, and add a note to the README.
