### ISSUE TITLE
HtmlReporter fails on start when removing old report

### ISSUE THREAD

**Issue by kirs** [kern/minitest-reporters#207]
In HtmlReporter, there is a line that tries to remove older html file: 
https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/html_reporter.rb#L79

On my case, HtmlReporter crashes on this line because I don't have old html file yet on the first start:

```
Emptying /app/log/minitest
/opt/ruby/2.2.0/gems/minitest-reporters-1.1.8/lib/minitest/reporters/html_reporter.rb:79:in `delete': No such file or directory @ unlink_internal - /app/log/minitest/index.html (Errno::ENOENT)
```

cc @rthbound

**Comment by os97673** [comment]
Thanks, fixed.
