### ISSUE TITLE
RubyMine reporter doesn't work with RubyMine 2016.1.1

### ISSUE THREAD

**Issue by pedroadame** [kern/minitest-reporters#210]
### Expected result
Rubymine reporter is used

### Actual result:
```
RubyMine reporter works only if it test was launched using RubyMine IDE or TeamCity CI server !!!
Using default results reporter...
```
is displayed. The default reporter is used.

### Steps to reproduce
Add `gem 'minitest-reporters'` to `Gemfile`
Run `bundle install`
Add:
```
require 'minitest/reporters'
Minitest::Reporters.use! Minitest::Reporters::RubyMineReporter.new
```
to `test_helper.rb`
Execute the `rake test` default configuration from Rubymine

### Notes
Rubymine version: 2016.1.1
RVM version: 1.27.0
Ruby version: 2.3.0p0
Bundler version: 1.12.1
RubyGems version: 2.5.1
OS: Debian Testing x64

**Comment by os97673** [comment]
what version of minitest-reporters do you use?

**Comment by pedroadame** [comment]
@os97673 `bundle show minitest-reporters` lists `minitest-reporters-1.1.9` directory, so I bet `1.1.9` =)

**Comment by os97673** [comment]
Thanks, I will look at this, but in a mean time I'd suggest to downgrade the gem to 1.1.8 (I hope should work ;)

**Comment by pedroadame** [comment]
Hi @os97673, I tried it without downgrading in a new project and it works flawlessly :/ Maybe is a compatibility problem. I'm closing this issue. If you need, reopen this!

**Comment by os97673** [comment]
most likely this is a bug/issue with RubyMine way to detect minitest.  I'd suggest to report this to them.
