### ISSUE TITLE
ProgressReporter erroneously counts 0 total tests and emits warning when used with minitest-focus

### ISSUE THREAD

**Issue by mattbrictson** [kern/minitest-reporters#217]
I am trying to use [minitest-focus](https://github.com/seattlerb/minitest-focus) with minitest-reporters, specifically using the ProgressReporter format.

To summarize minitest-focus: if you put `focus` immediately before a test method, only that single test will be executed; all others will be ignored. For example:

``` ruby
class Chandler::ConfigurationTest < Minitest::Test
  focus
  def test_default_git
    # ...
  end

  # other tests are ignored
end
```

However this screws up ProgressReporter. When `focus` is used, ProgressReporter somehow thinks that 0 tests are being executed, when in fact 1 test is being executed. And a progress bar with 0 length causes problems. Here's what happens:

```
Started with run options "-n=/^(Chandler::ConfigurationTest\\#test_default_git)$/" --seed 10224

  0/0: [==================================================================================] 100% Time: 00:00:00, Time: 00:00:00
 FAIL["test_default_git", Chandler::ConfigurationTest, 0.0022607849996347795]
 test_default_git#Chandler::ConfigurationTest (0.00s)
        Expected: "../test/git"
          Actual: "../test/.git"
        /Users/mbrictson/Code/chandler/test/chandler/configuration_test.rb:22:in `test_default_git'

  0/0: [==================================================================================] 100% Time: 00:00:00, Time: 00:00:00
WARNING: Your progress bar is currently at 0 out of 0 and cannot be incremented. In v2.0.0 this will become a ProgressBar::InvalidProgressError.
  0/0: [==================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00462s
1 tests, 2 assertions, 1 failures, 0 errors, 0 skips
```

You can see that 1 test executed, but the progress bar reported 0. Furthermore the warning indicates that this will completely crash when ruby-progressbar 2.0.0 is released.

My guess is that `DelegateReporter#total_count` ([source](https://github.com/kern/minitest-reporters/blob/9d3f5777c1a45e576a0c6844fa1f612831768595/lib/minitest/minitest_reporter_plugin.rb#L35-L42)) is to blame here, but I haven't gotten much further than that. Any ideas?

**Comment by os97673** [comment]
Need to looks how list of tests is collected now in minitest.

**Comment by dgdosen** [comment]
need help?

**Comment by os97673** [comment]
Help is always welcome :)

**Comment by os97673** [comment]
The first step to help: please provide a test project which reproduces the problem

**Comment by mattbrictson** [comment]
Good news! This no longer seems to be an issue with the latest versions of minitest-focus and minitest-reporters. Closing.
