### ISSUE TITLE
error with Minitest 5.10

### ISSUE THREAD

**Issue by brucek** [kern/minitest-reporters#219]
I get the following error:

    # Running tests with run options --seed 31173:

    /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:667:in `block in prerecord': undefined method `prerecord' for #<Minitest::Reporters::DelegateReporter:0x007f86811c5250> (NoMethodError)
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:666:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:666:in `prerecord'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:322:in `run_one_method'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:310:in `block (2 levels) in run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:309:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:309:in `block in run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:349:in `on_signal'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:336:in `with_info_handler'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:308:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:158:in `block in __run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:158:in `map'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:158:in `__run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:135:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.3@havn/gems/minitest-5.10.0/lib/minitest.rb:62:in `block in autorun'

all I am doing is this in `testhelper.rb`:

    Minitest::Reporters.use! Minitest::Reporters::MeanTimeReporter.new

I'm guessing `DelegateReporter` should just inherit from `Minitest::Reporter` (or a subclass - instead of just implementing prerecord) to also prevent these issues in the future, but I haven't dug deep enough to be sure...

**Comment by brucek** [comment]
PR in #220 - looks like Minitest::AbstractReporter made the most sense to subclass, I think

**Comment by zenspider** [comment]
I can also put out 5.10.1 that does a respond_to? check today... if that helps smooth things out.

**Comment by zenspider** [comment]
I just released minitest 5.10.1 to patch this up until this gets fixed.
