### ISSUE TITLE
The 2 'completion time' in the HTML report is inconsistent

### ISSUE THREAD

**Issue by s101070791** [kern/minitest-reporters#228]
![html report](https://cloud.githubusercontent.com/assets/19815750/24892784/b0c257cc-1eb1-11e7-80eb-9571ea713586.png)

Actual completion time：finished in 2033.8633s

**Comment by os97673** [comment]
the first time (upper-left corner) shows total time we spent to run something, the second one show time we spent for the suite. They might be different it is hard to say w/o details why you have such a big difference.
