### ISSUE TITLE
stack level too deep in `methods_matching'

### ISSUE THREAD

**Issue by Pepan** [kern/minitest-reporters#233]
Hi. 
There is some problem in Using minitest-reporters 1.1.15 !

When I run single test
`.../.rvm/rubies/ruby-2.4.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Itest /...../test/controllers/admin/players_controller_test.rb --name=test_admin_should_show_player`

I got Error:

`/.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest.rb:278:in `methods_matching': stack level too deep (SystemStackError)
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest/test.rb:61:in `runnable_methods'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:41:in `map'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:41:in `total_count'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:55:in `block in init_all_reporters'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:52:in `each'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:52:in `init_all_reporters'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:47:in `all_reporters'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-reporters-1.1.15/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
	 ... 11439 levels...
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest.rb:670:in `each'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest.rb:670:in `start'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest.rb:134:in `run'
	from /.../.rvm/gems/ruby-2.4.1/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'`

Falling back to minitest-reporters 1.1.14 solves the problem.

**Comment by os97673** [comment]
Could you please provide the test project to reproduce the problem?

**Comment by Pepan** [comment]
Hallo. It happens in two different projects Rails 5.1.3, ruby 2.4.1
First is clean API project and second is Normal HTML CSS project.

Gemfile from API project
```ruby
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.3'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry'
  gem 'rubocop', '~> 0.49.0', require: false
  gem 'rest-client'
  gem 'bullet'
  gem 'active_record_query_trace'
end

group :test do
  gem "minitest"
  gem 'minitest-reporters', '1.1.14'
  gem 'sucker_punch'
  gem 'minitest-profile'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# gem 'devise'
# gem 'simple_token_authentication', '~> 1.0'

gem 'rolify'
gem 'cancancan'

gem 'mini_magick'
gem 'carrierwave'
gem 'carrierwave-base64'

gem 'geocoder'

gem 'exception_notification'

gem 'savon', :git => 'https://github.com/MMacku/savon.git'

```

I'm little in hurry I can prepare testing project few days later.

**Comment by os97673** [comment]
Will wait for the project.

**Comment by Paxa** [comment]
I manage to separate it:
```ruby
gem 'minitest', '5.10.3'
gem 'minitest-reporters', '1.1.15'

require 'minitest/autorun'
require "minitest/reporters"

Minitest::Reporters.use!(
  Minitest::Reporters::DefaultReporter.new(color: true)
)

describe "example" do
  it "should nothing" do
    assert_equal(1 + 2, 3)
  end

  it "should" do
    assert_equal(1 + 2, 3)
  end
end
```

Run as:
```
ruby test.rb -n a
```

Only fail when:
* running with `-n ...` argument (or `m test.rb:12`)
* file has more then 1 tests

**Comment by codebycliff** [comment]
I'm getting this as well when upgrading from `1.1.14` to `1.1.15`, but only when running my tests through RubyMine. If I run the tests in the console, it works fine.

**Comment by os97673** [comment]
fixed, new version published
