### ISSUE TITLE
Gets autoloaded whether or not it's required

### ISSUE THREAD

**Issue by pnomolos** [kern/minitest-reporters#235]
I was trying to put a PR together for `minitest-parallel_fork` to work with `minitest-reporters`, and was banging my head against the wall until I realized that `minitest` autoloads plugins based on filename (see https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L85), which means `minitest_reporter_plugin.rb` will be loaded whether or not it's `require`d.  Is this the intended behaviour?

**Comment by os97673** [comment]
This is intended behavior of minitest.  I personally do not like this approach but this is how minitest expects reporters to work thus we follow the rule. I'd suggest to discuss this with minitest's maintainers (feel free to add me to the discussion).

**Comment by pnomolos** [comment]
@os97673 Would you be open to the possibility of making the loading of `minitest_reporter_plugin.rb` by MT a no-op so the classes aren't loaded and overridden until you actually require `minitest/reporters`?  That would allow you to *not* load even if you've got it in your Gemfile (via `require: false`).

**Comment by pnomolos** [comment]
@os97673 On this same vein, would you be open to a PR that overrides things for `minitest-parallel_fork` (if it's available)?  That gem now has a method you can override to detect which stats reporter to use :) -> https://github.com/jeremyevans/minitest-parallel_fork/commit/a3c55aa3292c4357f8e1d0390c1a8f6613467236

**Comment by os97673** [comment]
> @os97673 Would you be open to the possibility of making the loading of minitest_reporter_plugin.rb by MT a no-op so the classes aren't loaded and overridden until you actually require minitest/reporters? That would allow you to not load even if you've got it in your Gemfile (via require: false).

I think is it ok just we (kind of) expect user to call use! method



> @os97673 On this same vein, would you be open to a PR that overrides things for minitest-parallel_fork (if it's available)? That gem now has a method you can override to detect which stats reporter to use :) -> jeremyevans/minitest-parallel_fork@a3c55aa

I'm not sure I do understand the idea but open for discussion, so feel free to file the PR and we will discuss it.
