### ISSUE TITLE
1.1.18 - issue with using the --fail-fast flag

### ISSUE THREAD

**Issue by sleepingstu** [kern/minitest-reporters#239]
It appears the latest update to `minitest-reporters` has introduced a bug where running the tests using the `-f` or `--fail-fast` flag causes all tests to run regardless of success or failure.

Downgrading to `1.1.17` or commenting out the use of `minitest-reporters` in my `test_helper.rb` file in my Rails project reintroduces the expected behaviour of stopping on the first test that fails.

**Expected:**

Run tests using `rails test -f` and expect the first failing test raised should stop the running of the rest of the tests.

**Actual:**

Run tests using `rails test -f` and all tests run regardless of success or failure.

**My Setup:**

* Ruby 2.3.4
* Rails 5.0.6
* Minitest Rails 3.0.0
* Minitest Reporters 1.1.18

**Comment by os97673** [comment]
could you please provide simple test repo to reproduce the problem

**Comment by sleepingstu** [comment]
Sorry @os97673 I totally missed your reply. I'll try and get something put together.

**Comment by sleepingstu** [comment]
@os97673 here is something I've thrown together - https://github.com/sleepingstu/minitest-reporters-fail-fast-demo

The test setup is pretty much the same as my work projects, and there is a failing test in the home controller.

If you check the code out and run it, it should be using minitest reporter 1.1.18 and all the tests will run regardless of failure. If you comment in version 1.1.17 in the `Gemfile` (line 38) and re-run the tests then they should fail when the failure is it. 

Let me know if this helps...

**Comment by os97673** [comment]
Could you please test with 1.1.19 (I believe it should be fixed there).  Please reopen if it is not.

**Comment by sleepingstu** [comment]
Sorry for another late reply... can confirm this works as expected. Nice work!
