### ISSUE TITLE
Version 1.1.18, no output to my CI_REPORTS directory

### ISSUE THREAD

**Issue by matobinder** [kern/minitest-reporters#241]
I just noticed that after I upgraded some gems, I stopped getting any xml output to my CI_REPORTS directory.
I narrowed it down, and on my older base line that works, if I just update from 1.1.17 to 1.1.18 I stop getting results in my ENV['CI_REPORTS'] directory.

I'm going to try to widdle this down to a nice defined test case/repo. Any ideas why this might be be broken?
I'm using Ruby 2.3.0p0, on CentOS 7.4
I'll try to get more info on tracking this.

**Comment by matobinder** [comment]
I created a repo, and README.md file in it that should explain how to reproduce this
https://github.com/matobinder/demo-minitest-issue

**Comment by os97673** [comment]
I've reverted fix for #236 and published 1.1.19
