### ISSUE TITLE
Version 1.1.18, no longer works with minitest-line output

### ISSUE THREAD

**Issue by nathanpalmer** [kern/minitest-reporters#244]
We have minitest-line installed along with minitest-reporters and previously both of them would output just fine. Here is an example of the Spec reporter and the line output at the bottom.

![image](https://user-images.githubusercontent.com/125599/33026474-7bd11850-cdde-11e7-9fff-976cf5d30cb6.png)

However, as soon as we upgraded to 1.1.18 the minitest-line output no longer shows. I suspect it might be similar to #241.

We have `minitest-reporter` 1.1.18 installed and `minitest-line` 0.6.4 installed.

Let me know what else you might need to see/reproduce this.

**Comment by os97673** [comment]
Could you please test with 1.1.19 (I believe it should be fixed there).  Please reopen if it is not.

**Comment by nathanpalmer** [comment]
@os97673 Just verified that it's working on 1.1.19. Thanks!
