### ISSUE TITLE
List of options / overrides for reporters

### ISSUE THREAD

**Issue by jbhandari** [kern/minitest-reporters#246]
Hi there,

I cannot seem to find a list of available options per reporter that we can use to get the output we require.

For example you added this call in the __README__:
`Minitest::Reporters.use! [Minitest::Reporters::DefaultReporter.new(:color => true)]`

So I know how I can toggle color in the DefaultReport. What about the other reporters? Is there a list I am missing or do I need to go through source code?

I am looking to use SpecReporter but not have it print the Test Class or Test Name. Just show PASS/FAIL and the metrics. 

Any help or direction would be much appreciated!

**Comment by os97673** [comment]
1. you have to read the code
2. I'd expect SpecReporter to print test name: here is a sample output
```
MinitestReportersTest::GoodTest
  test_b                                                          PASS (0.00s)
  test_a                                                          PASS (0.00s)

MinitestReportersTest::BadTest
  test_boom                                                      ERROR (0.00s)
```
If in your case it doesn't please file a bug with steps to reproduce the problem
