### ISSUE TITLE
v1.3.1 raises loading errors

### ISSUE THREAD

**Issue by rmm5t** [kern/minitest-reporters#267]
v1.3.1 started breaking all our builds this morning. I haven't had a chance to investigate exactly why yet, but below is a stack trace. 

Workaround: Rollback to v1.3.0

```
/Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:114:in `const_get': wrong constant name initialize (NameError)
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:114:in `block in load_constant'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:113:in `each'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:113:in `inject'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:113:in `load_constant'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:62:in `test_class'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:18:in `before_test'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/default_reporter.rb:37:in `before_test'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters.rb:47:in `block in run_with_hooks'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters.rb:47:in `each'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters.rb:47:in `run_with_hooks'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
	from /Users/dir/vendor/bundle/ruby/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```

**Comment by notEthan** [comment]
base_reporter tries to load the constant referenced by the test class name, but the name is not a valid constant name for classes defined by describe blocks. should not be trying to load the constant by this class name.

**Comment by mateuszgorniak** [comment]
Agree, I implemented some integration specs where the main block is not the name of the existing class but describes tested functionality. I had to rollback to v1.3.0 as well.

**Comment by prettycoder** [comment]
same here:
`/root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:114:in 'const_get': uninitialized constant Rails5x (NameError)`

rolling back ...

**Comment by os97673** [comment]
this is a regression from fix for #265 :(

**Comment by os97673** [comment]
if someone can create a unit test to catch the problem it would be a great help for me (for some reasons current tests don't catch it :(
In any case I will try to work on this over weekend

**Comment by prettycoder** [comment]
Are you still looking for a unit test? Sorry, for the late answer.
I can create one for you.
The short answer is that my failing tests start like this:
```
require "minitest_helper"
describe "Rails5x" do
    ...
```

**Comment by prettycoder** [comment]
Ok, here it is
```
require 'minitest/spec'
require 'minitest/autorun'
require 'minitest/reporters'

MiniTest::Reporters.use! MiniTest::Reporters::SpecReporter.new

describe 'Rails5x' do
  it 'should expose the reporter bug' do
    true.must_equal true
  end
end
```

**Comment by prettycoder** [comment]
Unit test that can be added to spec_reporter_test.rb
```
    def test_report_for_describe_not_using_const
      klass = describe("whatever") { it("passes") { assert true } }
      runnable = klass.runnable_methods.first

      # Run the test
      result = klass.new(runnable).run
      @reporter.start
      @reporter.record(result)

      begin
        @reporter.report
      rescue => e
        error_msg = "error executing @reporter.report, #{e}"
      end

      refute error_msg, error_msg
    end
```
I tried a stab at a fix, but I'm unsure if returning a String, when the klass errors on const_get is the right thing to do. Would need more test coverage. In base_reporter.rb:
```
      def load_constant(name)
        name.to_s.split('::').inject(Object) do |namespace, const_name|
          return name unless const_name =~ /^[A-Z]/
          namespace.const_defined?(const_name) ? namespace.const_get(const_name) : name
        end
      end
```

**Comment by jesperronn** [comment]
@prettycoder @os97673 Maybe add the suggestion as a pull-request will be easier for maintainers to merge. Please create pull request, and refer this issue.

PS. I also had to roll pack to v 1.3.0, and think it is urgent to get a fix out.

**Comment by os97673** [comment]
the test is not failing :(  Help needed.

**Comment by prettycoder** [comment]
I'm sorry, I should have done the PR myself. 
I'm wondering if you need to move one `end`, so that the test is within the SpecReporterTest class. 
I'll be back at work in 12 hours and can help more.

**Comment by prettycoder** [comment]
BTW: I checked the methods -- mainly `report` in minitest-reporter and minitest -- that use the result from `load_constant` and it looks like returning a String won't break anything.

**Comment by os97673** [comment]
My bad, mostly android developer nowdays and my current environment is not very friendly :( Windows)

**Comment by os97673** [comment]
let's move discussion to #268

**Comment by rmm5t** [comment]
You don’t close an issue because there’s an open pull request. Instead, you reference the issue in the pull request so the issue auto-closes when the pull request is merged. ¯\_(ツ)_/¯

**Comment by os97673** [comment]
For me both the PR and the issue is the same (PR is just more convenient to work with) and I see no reason to keep both opened.

**Comment by os97673** [comment]
1.3.2.beta1 has been release, please test

**Comment by jsantos** [comment]
@os97673 It's working fine here!

**Comment by jesperronn** [comment]
also works for me:

`gem "minitest-reporters", "~>1.3.2.beta1", require: false`
