### ISSUE TITLE
Time.current is provided by Active Support

### ISSUE THREAD

**Issue by cstyles** [kern/minitest-reporters#293]
This line in `lib/minitest/templates/index.html.erb` calls `Time.current` which is defined in Active Support. Please consider replacing it with `Time.now` or requiring Active Support as a dependency.

https://github.com/kern/minitest-reporters/blob/c37eebae52ebca9c96f3400b92ae4b74081451a7/lib/minitest/templates/index.html.erb#L14

**Comment by os97673** [comment]
Fixed, thank you for reporting.
