### ISSUE TITLE
Add a TAPS (test anything protocol) formatter

### ISSUE THREAD

**Issue by jeffblake** [kern/minitest-reporters#299]
I'm setting up CI on Heroku and it would be great if there was a TAP formatter available.

https://testanything.org/

Thanks :)

**Comment by lukeredpath** [comment]
+1 - I've tried to integrate minitap but I can't get it working properly, it always exits with a non-zero exit code even though the tests are passing.

**Comment by clinejj** [comment]
This article by @davidwessman had a good overview of a custom TAP reporter built based off the `ProgressReporter`: https://dev.to/davidwessman/rails-minitest-results-output-in-tap-format-for-heroku-ci-46d3

Basic steps:
- take the gist here: https://gist.github.com/davidwessman/09a13840a8a80080e3842ac3051714c7#file-tap_reporter-rb
- Add it to `lib/minitest/reporters/tap_reporter.rb`
- Add the following to your `test_helper.rb` to always run, or you can ignore the second line and pass in through the environment variable
  ```ruby
  require Rails.root.join('lib/minitest/reporters/tap_reporter.rb')
  Minitest::Reporters.use! Minitest::Reporters::TapReporter.new
  ```

**Comment by davidwessman** [comment]
> This article by @davidwessman had a good overview of a custom TAP reporter built based off the `ProgressReporter`: https://dev.to/davidwessman/rails-minitest-results-output-in-tap-format-for-heroku-ci-46d3

What a nice surprise that someone needed this! Please reach out if you have any questions.

I just updated the Gist with the latest code I use where I updated the failure message to use `message_for`:
https://gist.github.com/davidwessman/09a13840a8a80080e3842ac3051714c7#file-tap_reporter-rb-L19

**Comment by itsliamegan** [comment]
I'm familiar with TAP from the JS world ([tape](https://www.npmjs.com/package/tape) is a decently popular package) but I haven't seen anybody using it for Ruby until now. Given that, I'm inclined to say that this should stay in user land, maybe with a link in the README to @davidwessman's gist? Unless TAP is more popular in Ruby-land than I'm aware, I feel like the maintenance burden is too great given that it can be solved with 40LOC in your own projects

**Comment by clinejj** [comment]
We switched to that format for reporting because Heroku's CI has some special UX it does when a test run reports in TAP: https://devcenter.heroku.com/articles/heroku-ci-technical-detail-on-ci-lifecycle#step-5-the-test-run-is-executed

**Comment by davidwessman** [comment]
A great great place for it would be the Heroku ruby buildpack. But I do not think anyone wants to support it, perhaps it makes more sense with a blog post and some gists.

**Comment by itsliamegan** [comment]
I agree with @davidwessman. Since this is possible in user land, we'll close this. I've opened #309 to add a note to the readme

**Comment by ambethia** [comment]
Thanks for adding the note to the README on this, I appreciate it! I was just looking for how to do TAP output from minitest, so I was happy to find this recently added.

Is there any reason we would be opposed to including this TAP formatter as part of `minitest-reporters` itself?

**Comment by davidwessman** [comment]
http://github.com/davidwessman/blinka_reporter

I have added a TAP-reporter to my open-source gem that no longer relies on `minitest-reporters`.
